### ISSUE TITLE
[新增Docker-Compose] 最近其他应用出现使用action封仓现象

### ISSUE THREAD

**Issue by Jox2018** [GamerNoTitle/bilibiliJudge#11]
最近其他应用出现使用action封仓现象，大佬可以尽快出docker-compose布置嘛

**Comment by GamerNoTitle** [comment]
Docker版做是可以做，但是短期内肯定出不来，我手头事情有点多，而且下周有二模，已经被关在学校十多天了
如果你有经验可以自己做一下，没有的话，emmmm，那估计只能等我有空才能做了
其实如果你怕封号的话可以丢到阿里或腾讯的云函数上去跑，小改一下就能正常使用了

Sent by using Sony Ericsson W595C

---- 原始信息 ----
发自: Jox2018 ***@***.***>
发送时间: 
收件人: GamerNoTitle/bilibiliJudge ***@***.***>
抄送: Subscribed ***@***.***>
主题: [GamerNoTitle/bilibiliJudge] 最近其他应用出��使用action封仓现象 (#11)

最近其他应用出现使用action封仓现象，大佬可以尽快出docker-compose布置嘛

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/GamerNoTitle/bilibiliJudge/issues/11

**Comment by GamerNoTitle** [comment]
还是第一次听说会封仓库，具体怎么表现的？　

Sent by using Sony Ericsson W595C

**Comment by Jox2018** [comment]
有人用actions挖矿，长时间定时任务，github有时候会波及无辜

**Comment by Jox2018** [comment]
我可以试着做一个docker-compose

**Comment by GamerNoTitle** [comment]
可以，你做完我直接和并也行
挖矿就真的是滥用。。。　

Sent by using Sony Ericsson W595C

---- 原始信息 ----
发自: Jox2018 ***@***.***>
发送时间: 
收件人: GamerNoTitle/bilibiliJudge ***@***.***>
抄送: Pesy Wu ***@***.***>, Comment ***@***.***>
主题: Re: [GamerNoTitle/bilibiliJudge] 最近其他应用出��使用action封仓现象 (#11)

我可以试着做一个docker-compose

**Comment by GamerNoTitle** [comment]
对了，做的时候不要带action保活脚本里的UUID.txt文件，如果已经有了就先git reset回去一下，3Q

Sent by using Sony Ericsson W595C

**Comment by GamerNoTitle** [comment]
我用我不成熟的Docker技术做了一个 在Docker分支 你可以试试

**Comment by Jox2018** [comment]
这个docker有一些小问题，我修改完以后提交到这个分支。docker-compose的环境变量没用，dockerfile设置才有用，我找找哪里出了问题，还有其他一些小问题我改了

**Comment by Jox2018** [comment]
原始版本修改后，已验证通过，dockerHub和定时在路上了

**Comment by Jox2018** [comment]
小哥给个微信可以嘛

**Comment by GamerNoTitle** [comment]
微信就算了，扣扣3559869084或者telegram搜＠GamerNoTitle

Sent by using Sony Ericsson W595C

---- 原始信息 ----
发自: Jox2018 ***@***.***>
发送时间: 
收件人: GamerNoTitle/bilibiliJudge ***@***.***>
抄送: Pesy Wu ***@***.***>, Comment ***@***.***>
主题: Re: [GamerNoTitle/bilibiliJudge] [新增Docker-Compose] 最近其他应用出��使用action封仓现象 (#11)

小哥给个微信可以嘛

**Comment by GamerNoTitle** [comment]
个人更偏向于用telegram　　
:-)
Sent by using Sony Ericsson W595C

**Comment by Jox2018** [comment]
叮了
:-)

**Comment by GamerNoTitle** [comment]
https://t.me/GamerNoTitle　

Sent by using Sony Ericsson W595C

**Comment by Jox2018** [comment]
tg24小时在线

**Comment by GamerNoTitle** [comment]
晚点合并，现在没电脑:-D　

Sent by using Sony Ericsson W595C

---- 原始信息 ----
发自: Jox2018 ***@***.***>
发送时间: 
收件人: GamerNoTitle/bilibiliJudge ***@***.***>
抄送: Pesy Wu ***@***.***>, Comment ***@***.***>
主题: Re: [GamerNoTitle/bilibiliJudge] [新增Docker-Compose] 最近其他应用出��使用action封仓现象 (#11)

tg24小时在线
